# Generated by Django 4.0.4 on 2022-05-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('max_vote', models.IntegerField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('persons', models.ManyToManyField(to='poll_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_app.person')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_app.poll')),
            ],
        ),
    ]
