# Generated by Django 4.0.4 on 2022-05-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='vote',
            new_name='poll',
        ),
    ]
