# Generated by Django 4.0.4 on 2022-05-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0002_rename_vote_votes_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_active',
        ),
    ]
