# Generated by Django 4.0.4 on 2022-05-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0003_remove_poll_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_start',
            field=models.DateField(),
        ),
    ]
