# Generated by Django 4.0.4 on 2022-05-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0005_poll_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
